import math
from graphics import *
def main():
    radius = eval(input("Enter radius: "))
    yi = eval(input("Enter y intercept: "))
    win = GraphWin()
    win.setCoords(-10,-10,10,10)
    c = Circle(Point(0,0),radius)
    c.draw(win)
    l = Line(Point(-10,yi),Point(10,yi))
    l.draw(win)
    x = math.sqrt(abs((radius*radius)-(yi*yi)))
    p1 = Point(x,yi)
    p1.draw(win)
    p1.setFill('red')
    p2 = Point(-x,yi)
    p2.draw(win)
    p2.setFill('red')
    s = Text(Point(0,-3),"X values are +/-")
    s.setSize(10)
    s.draw(win)
    t = Text(Point(0,-6),x)
    t.draw(win)
main()
