import math
from graphics import *
def main():
    print("This program draws a Circle and Y-intercept based on user inputs")
    radius = eval(input("Enter radius: "))
    yi = eval(input("Enter y intercept: "))
    win = GraphWin()
    win.setCoords(-10,-10,10,10)
    c = Circle(Point(0,0),radius)
    c.draw(win)
    l = Line(Point(-10,yi),Point(10,yi))
    l.draw(win)
    x = math.sqrt(abs((radius*radius)-(yi*yi)))
    point1 = Point(x,yi)
    point1.draw(win)
    point1.setFill('red')
    point2 = Point(-1*x,yi)
    point2.draw(win)
    point2.setFill('red')
    s = Text(Point(-3,-6),"X values are:")
    s.setSize(10)
    s.draw(win)
    x = round(x,2)
    t1 = Text(Point(2.5,-6),x)
    t1.draw(win)
    tOr = Text(Point(5,-6),"Or,")
    tOr.draw(win)
    t2 = Text(Point(8,-6),-x)
    t2.draw(win)
    ex = Text(Point(-4,7),"Click to exit")
    ex.setSize(12)
    ex.draw(win)
    win.getMouse()
    win.close()
main()
